# Generated by Django 2.2.2 on 2020-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementcompressive',
            name='test_title',
            field=models.CharField(default="Put your Test's Title Here", max_length=50),
        ),
    ]
