# Generated by Django 2.2.2 on 2020-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_cementcompressive_test_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cementcompressive',
            name='test_title',
        ),
        migrations.AddField(
            model_name='cementcompressive',
            name='test_name',
            field=models.CharField(default='Cement Compressive Test', max_length=500),
        ),
    ]
